### ISSUE TITLE
新版本在MIUI12中无法正常生效

### ISSUE THREAD

**Issue by wwlwwlwwlwwl** [577fkj/MIUIStatusBarLyric#2]
**环境信息**

模块版本: 3.31.1(53)
MIUI版本: 12.0.22.0(RKBCNXM)
Android版本: 11
屏幕类型: AMOLED

**在最新的release版本中能否复现**
在3.31.1(53)和3.30.0(52)中均可复现，但是在老版本2.22.42(47)中正常工作

**bug内容**

在使用最新版本的时候，状态栏无法显示任何歌词  
对模块，系统UI，网易云使用重新优化均无效    
使用模块中的关于模块->开发测试->显示测试歌词，在老版本中会显示出测试，但是新版本中没有任何效果，每次测试前都已重启系统UI  
**复现方法**

使用老版本模块2.22.42，安装后打开状态栏歌词功能，重启系统UI，进入开发测试，进行显示测试，可以正常工作
![Screenshot_2021-11-28-10-36-15-294_miui statusbar lyric](https://user-images.githubusercontent.com/47500260/143726696-961a3e5c-a13b-4c3c-8b6b-9185171e0ee7.png)
再次安装最新版本3.31.3，打开状态栏歌词功能，重启系统UI，再次测试，无效  
回退至老版本，重新重复以上测试，可以正常生效

**Comment by wwlwwlwwlwwl** [comment]
[老版本.zip](https://github.com/577fkj/MIUIStatusBarLyric/files/7612717/default.zip)
[新版本.zip](https://github.com/577fkj/MIUIStatusBarLyric/files/7612719/default.zip)
老版本与新版本中的日志，新版本中无法使用似乎是因为寻找NotificationEntryManager失败了
`[ 2021-11-28T10:44:42.079     1000: 12226: 12226 E/LSPosed-Bridge  ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13)
	at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:0)
	at miui.statusbar.lyric.hook.MainHook.handleLoadPackage(:1)
	at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2)
	at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6)
	at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28)
	at D1.afterHookedMethod(Unknown Source:111)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.getClassLoader(Unknown Source:8)
	at android.app.LoadedApk.getResources(LoadedApk.java:1192)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2671)
	at android.app.ContextImpl.createAppContext(ContextImpl.java:2663)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716)
	at java.lang.reflect.Method.invoke(Native Method)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107)
	at LspHooker_.handleBindApplication(Unknown Source:11)
	at android.app.ActivityThread.access$1400(ActivityThread.java:246)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:233)
	at android.app.ActivityThread.main(ActivityThread.java:7892)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:454)
	at A0.a(Unknown Source:24)
	at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5)
	... 23 more
Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager
	... 27 more`

**Comment by MisaLiu** [comment]
类原生魔趣安卓9，与楼主问题相同，报错也一样

正尝试旧版本是否可用

**Comment by 577fkj** [comment]
> [老版本.zip](https://github.com/577fkj/MIUIStatusBarLyric/files/7612717/default.zip) [新版本.zip](https://github.com/577fkj/MIUIStatusBarLyric/files/7612719/default.zip) 老版本与新版本中的日志，新版本中无法使用似乎是因为寻找NotificationEntryManager失败了 `[ 2021-11-28T10:44:42.079 1000: 12226: 12226 E/LSPosed-Bridge ] de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:13) at de.robv.android.xposed.XposedHelpers.findAndHookMethod(Unknown Source:0) at miui.statusbar.lyric.hook.MainHook.handleLoadPackage(:1) at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(Unknown Source:2) at de.robv.android.xposed.callbacks.XC_LoadPackage.call(Unknown Source:6) at de.robv.android.xposed.callbacks.XCallback.callAll(Unknown Source:28) at D1.afterHookedMethod(Unknown Source:111) at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136) at LspHooker_.getClassLoader(Unknown Source:8) at android.app.LoadedApk.getResources(LoadedApk.java:1192) at android.app.ContextImpl.createAppContext(ContextImpl.java:2671) at android.app.ContextImpl.createAppContext(ContextImpl.java:2663) at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6716) at java.lang.reflect.Method.invoke(Native Method) at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:107) at LspHooker_.handleBindApplication(Unknown Source:11) at android.app.ActivityThread.access$1400(ActivityThread.java:246) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1946) at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loop(Looper.java:233) at android.app.ActivityThread.main(ActivityThread.java:7892) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967) Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager at java.lang.Class.classForName(Native Method) at java.lang.Class.forName(Class.java:454) at A0.a(Unknown Source:24) at de.robv.android.xposed.XposedHelpers.findClass(Unknown Source:5) ... 23 more Caused by: java.lang.ClassNotFoundException: com.android.systemui.statusbar.notification.NotificationEntryManager ... 27 more`

最新的dev版本已修复此问题

**Comment by wwlwwlwwlwwl** [comment]
测试了网易云音乐和椒盐音乐,现在可以正常使用了
