### ISSUE TITLE
模块在 Mokee 安卓 9 环境下不生效

### ISSUE THREAD

**Issue by MisaLiu** [577fkj/MIUIStatusBarLyric#4]
**环境信息**

模块版本: v2.22.42（最新 v3.32.3 的问题见 [这个 issue](https://github.com/577fkj/MIUIStatusBarLyric/issues/2)）
MIUI版本: NaN
系统类型和版本: `Mokee mk_land-userdebug 9 PQ3A.190801.002 eng.buildb.20210623.222404 dev-keys`
Android版本: 9
屏幕类型: LCD

**在最新的release版本中能否复现**
最新 v3.32.3 的问题见 [这个 issue](https://github.com/577fkj/MIUIStatusBarLyric/issues/2)

**bug内容**

状态栏无法正常显示歌词，但能正常获取歌词。已确认使用了支持的播放器，已确认开启模块并选择作用域于 SystemUI。

**复现方法**

我提供一下日志吧

**日志**
```
[ 2021-11-30T18:09:41.040     1000:  5202:  5202 I/LSPosed-Bridge  ] Loading module miui.statusbar.lyric from /data/app/miui.statusbar.lyric-1Vr9yYG0aVq_2dO4TDhr6w==/base.apk
[ 2021-11-30T18:09:41.076     1000:  5202:  5202 I/LSPosed-Bridge  ]   Loading class miui.statusbar.lyric.hook.MainHook
[ 2021-11-30T18:09:41.092     1000:  5202:  5202 E/LSPosed-Bridge  ]     Failed to load class miui.statusbar.lyric.hook.MainHook
java.lang.ExceptionInInitializerError
	at d.a.a.g.c(Unknown Source:9)
	at d.a.a.g.<init>(Unknown Source:3)
	at miui.statusbar.lyric.hook.MainHook.<clinit>(Unknown Source:44)
	at java.lang.Class.newInstance(Native Method)
	at de.robv.android.xposed.XposedInit.initModule(Unknown Source:58)
	at de.robv.android.xposed.XposedInit.loadModule(Unknown Source:2)
	at de.robv.android.xposed.XposedInit.lambda$loadModules$0(Unknown Source:21)
	at de.robv.android.xposed.XposedInit.a(Unknown Source:0)
	at O2.accept(Unknown Source:12)
	at java.util.ArrayList.forEach(ArrayList.java:1262)
	at de.robv.android.xposed.XposedInit.loadModules(Unknown Source:2)
	at org.lsposed.lspd.core.Main.a(Unknown Source:15)
	at org.lsposed.lspd.core.Main.forkSystemServerPost(Unknown Source:21)
	at com.android.internal.os.Zygote.nativeForkSystemServer(Native Method)
	at com.android.internal.os.Zygote.forkSystemServer(Zygote.java:190)
	at com.android.internal.os.ZygoteInit.forkSystemServer(ZygoteInit.java:712)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:833)
Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] android.content.pm.IPackageManager.getPackagesForUid(int)' on a null object reference
	at android.os.storage.StorageManager.getVolumeList(StorageManager.java:1157)
	at android.os.Environment$UserEnvironment.getExternalDirs(Environment.java:91)
	at android.os.Environment.getExternalStorageDirectory(Environment.java:481)
	at d.a.a.h.<clinit>(Unknown Source:5)
	... 17 more

// ...

[ 2021-11-30T18:09:52.587    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： Debug已开启
[ 2021-11-30T18:09:52.595    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： 正在hook系统界面
[ 2021-11-30T18:09:52.667    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： hook系统界面结束
[ 2021-11-30T18:09:55.295    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： MIUI Ver:  IsEuMiui: false Android: 28
[ 2021-11-30T18:09:55.296    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： mStatusClock 反射失败: java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:67)
	at miui.statusbar.lyric.hook.MainHook$b.afterHookedMethod(:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.onViewCreated(Unknown Source:14)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```

**Comment by 577fkj** [comment]
请提供完整日志

**Comment by MisaLiu** [comment]
> 请提供完整日志

稍等我马上来

**Comment by 577fkj** [comment]
```
[ 2021-11-30T18:09:55.296    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： mStatusClock 反射失败: java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:67)
	at miui.statusbar.lyric.hook.MainHook$b.afterHookedMethod(:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.onViewCreated(Unknown Source:14)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
[ 2021-11-30T18:09:55.298    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： mClockView 反射失败: java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mClockView
java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mClockView
	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:67)
	at miui.statusbar.lyric.hook.MainHook$b.afterHookedMethod(:3)
	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
	at LspHooker_.onViewCreated(Unknown Source:14)
	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:193)
	at android.app.ActivityThread.main(ActivityThread.java:6718)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
```
请提供systemUI

**Comment by MisaLiu** [comment]
> ```
> [ 2021-11-30T18:09:55.296    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： mStatusClock 反射失败: java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
> java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mStatusClock
> 	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:67)
> 	at miui.statusbar.lyric.hook.MainHook$b.afterHookedMethod(:3)
> 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
> 	at LspHooker_.onViewCreated(Unknown Source:14)
> 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
> 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
> 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
> 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
> 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
> 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6718)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> [ 2021-11-30T18:09:55.298    10033: 15649: 15649 I/LSPosed-Bridge  ] MIUI状态栏歌词： mClockView 反射失败: java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mClockView
> java.lang.NoSuchFieldError: com.android.systemui.statusbar.phone.CollapsedStatusBarFragment#mClockView
> 	at de.robv.android.xposed.XposedHelpers.findField(Unknown Source:67)
> 	at miui.statusbar.lyric.hook.MainHook$b.afterHookedMethod(:3)
> 	at de.robv.android.xposed.LspHooker.handleHookedMethod(Unknown Source:136)
> 	at LspHooker_.onViewCreated(Unknown Source:14)
> 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1308)
> 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2426)
> 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2205)
> 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2161)
> 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2062)
> 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:738)
> 	at android.os.Handler.handleCallback(Handler.java:873)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6718)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:491)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> ```
> 
> 请提供systemUI

稍等

**Comment by 577fkj** [comment]
> CollapsedStatusBarFragment

暂时不支持此版本
因为hook路径不在通用位置
com.android.systemui.statusbar.phone.ClockController.mCenterClock : com.android.systemui.statusbar.policy.Clock

**Comment by MisaLiu** [comment]
> > CollapsedStatusBarFragment
> 
> 暂时不支持此版本 因为hook路径不在通用位置 com.android.systemui.statusbar.phone.ClockController.mCenterClock : com.android.systemui.statusbar.policy.Clock

那么请问一下有没有其他解

**Comment by 577fkj** [comment]
> > > CollapsedStatusBarFragment
> > 
> > 
> > 暂时不支持此版本 因为hook路径不在通用位置 com.android.systemui.statusbar.phone.ClockController.mCenterClock : com.android.systemui.statusbar.policy.Clock
> 
> 那么请问一下有没有其他解

自己修改代码 （
